import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='dark'>
      <body className='overflow-hidden bg-white text-slate-500 antialiased dark:bg-slate-900 dark:text-slate-400'>
        {children}
      </body>
    </html>
  );
}
